<?php

/**
 * @file bugsnag.module
 *
 * Integrates Drupal with Bugsnag for error tracking and alerting.
 */


/**
 * Retrieves the path to the PHP library for Bugsnag.
 */
function _bugsnag_get_library_path() {
  return DRUPAL_ROOT . '/sites/all/libraries/bugsnag/src/Bugsnag/Autoload.php';
}

/**
 * Implements hook_boot().
 */
function bugsnag_boot() {
  $apikey = trim(variable_get('bugsnag_apikey', ''));
  if (file_exists(_bugsnag_get_library_path()) && !empty($apikey)) {
    global $user;
    global $bugsnag_client;

    // inclujde library and instantiate
    require_once _bugsnag_get_library_path();
    $bugsnag_client = new Bugsnag_Client(variable_get('bugsnag_apikey', ''));

    // track user if logged in
    if ($user->uid) {
      $bugsnag_client->setUser(array(
        'id' => $user->uid,
        'name' => $user->name,
        'email' => $user->mail
      ));
    }

    // use bugsnag for all errors and exceptions
    set_error_handler(array($bugsnag_client, 'errorHandler'));
    set_exception_handler(array($bugsnag_client, 'exceptionHandler'));

  }
}